title: QwertyWorks
author: Intern
email: theintern@qwertyworks.com
description: > # this means to ignore newlines until "baseurl:"
  We sell light :D
github_username:  kamakshidasan

sass:
    style: compressed
